---
title: "Compute repeatability"
author: "Nicolas RODE"
date: "`r format(Sys.Date(), '%d-%B-%Y')`"
output: 
  html_document: 
    number_sections: yes
    theme: journal
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: no
editor_options: 
  chunk_output_type: console
---

# Simulate data
## Enter values for simulations
```{r }
library(ggplot2)
library(dplyr)
library(tidyr)

## Number of individual measured
n_ind=30
## Number of replicate per individual
k_rep=2

## Mean of the trait in the population
mean_trait=10

## Variance of the trait among individuals
var_among=1

## Variance among measurement of the trait within each individual
var_within=0.1

## Create dataset
data <- expand.grid(id=as.factor(1:n_ind), replicate=paste0("rep", 1:2))


```
## True value of the trait for each individual
```{r }
## Set a seed so that results can be reproduced
set.seed(123)

## Simulate true value of the trait for each individual
true_trait_value <- rnorm(n=n_ind, mean = mean_trait, sd = sqrt(var_among))

## Histogram with the distribution of the trait values across the n_ind individuals
p <- data_frame(trait = true_trait_value) %>%
          ggplot(., aes(trait)) + 
          geom_histogram(aes(y = after_stat(density)), colour = "black") +
          geom_vline(xintercept = mean_trait, linetype="dotted", color = "red", linewidth=1) + ## Add mean of the trait
          stat_function(fun = dnorm, linewidth=1, linetype="dotted", color = "red", geom = "line", args = list(mean = mean_trait, sd = sqrt(var_among))) ## Add expected distribution of the trait in the population
p

## Add new column with true value of the trait for each individual
data$true_trait_value <- rep(true_trait_value, k_rep)

```

## Measurement error
```{r }
## Add new column with measurement error
data$measurement_error <- rnorm(n=nrow(data), mean = 0, sd = sqrt(var_within))

## Histogram with the distribution of the measurement error across the n_ind * k_rep measurements
p <- data %>%
          ggplot(., aes(measurement_error)) + 
          geom_histogram(aes(y = after_stat(density)), colour = "black") +
          geom_vline(xintercept = 0, linetype="dotted", color = "red", linewidth=1) + ## Add mean of the trait
          stat_function(fun = dnorm, linewidth=1, linetype="dotted", color = "red", geom = "line", args = list(mean = 0, sd = sqrt(var_within))) 
p
```

## Observed trait values
```{r }
## Add new column with observed value of the trait for each replicate measurement of each individual
data$observed_trait_value <- data$true_trait_value + data$measurement_error

## Histogram with the distribution of the trait values across the n_ind * k_rep measurements
p <- data_frame(trait = true_trait_value) %>%
          ggplot(., aes(trait)) + 
          geom_histogram(aes(y = after_stat(density)), colour = "black") +
          geom_vline(xintercept = mean_trait, linetype="dotted", color = "red", linewidth=1) + ## Add mean of the trait
          stat_function(fun = dnorm, linewidth=1, linetype="dotted", color = "red", geom = "line", args = list(mean = mean_trait, sd = sqrt(var_among))) ## Add expected distribution of the trait in the population
p

## Plot correlation between the two measurements
data %>%
  select(id, replicate, observed_trait_value)%>%
  pivot_wider(names_from = replicate, values_from = observed_trait_value)%>%
          ggplot(aes(x=rep1, y=rep2)) +
          geom_point() +
          geom_abline(intercept = 0, slope=1, linetype="dotted", color = "red", linewidth=1) 
```


# Estimate repeatability with the ANOVA function
```{r }
## Number of replicate per individual
table(data$id)

## Fit model with ANOVA
fit0 <- aov(observed_trait_value ~ id, data = data)
summary(fit0)

## Number of replicates per individual
n0=k_rep

## Degrees of freedom = number of individual - 1
df_Among <- n_ind-1

## Sum of squares among individuals
SSA <- summary(fit0)[[1]]$`Sum Sq`[1] 

## Among-groups (ie individual) variance component
MSA <- SSA/df_Among

## residual degrees of freedom
dfRes <- n_ind*(n0-1) 

## Sum of squares among replicates
SSW <- summary(fit0)[[1]]$`Sum Sq`[2] 

## Within-group variance component = Residual variance
(VarWithin <- SSW/dfRes)

## Check that the value computed by R is the same
sigma(fit0)^2

## Among individual variance 
(VarAmong<- (MSA-VarWithin)/n0)

## Observed repeatability
(Repeatability <- VarAmong/(VarAmong+VarWithin))

## Expected repeatability
(R_expected=var_among/(var_among+var_within))

```

# Estimate repeatability by hand
## Fit complete model
```{r }
## Use the code from https://www.r-bloggers.com/2021/05/one-way-anova-by-hand/

## Compute the error of each measurement under the complete model, i.e. the difference between each measurement and the mean of two measurements of the same individual
## Compute the squared error of each measurement (complete model)
complete <- data %>%  
  group_by(id) %>% 
  mutate(mean_trait_value = mean(observed_trait_value)) %>% #in complete model, fit is the group mean (i.e. mean of each individual) 
  mutate(error = mean_trait_value - observed_trait_value) %>% 
  mutate(sq_error = error ^ 2) %>%
  ungroup()

## Compute the N, the total number of observations and the SSE, the sum of the squared error of each measurement
## Compute n, the number of groups in the complete model (ie. individuals in the dataset)
## Compute df2, the residual degrees of freedom
(complete <- complete %>% 
  summarise(N = n(), sse = sum(sq_error)) %>% 
  mutate(n = length(unique(data$id))) %>% 
  mutate(df2 = N - n) %>% 
  select(sse, df2, N, n) %>% 
  mutate(mse = sse / df2) # mse = sigma squared 
)

## Check that the value computed by R is the same
sigma(fit0)^2

```
## Fit reduced model
```{r }

## Compute the error of each measurement according to the reduced model, i.e. the difference between each measurement and the overall mean across all measurements in the dataset
## Compute the squared error of each measurement (reduced model)
reduced <- data %>%  
  mutate(mean_trait_value = mean(observed_trait_value)) %>% #in reduced model, fit is the overall mean 
  mutate(error = mean_trait_value - observed_trait_value) %>% 
  mutate(sq_error = error ^ 2) %>%
  ungroup() 

## Compute the N, the total number of observations and the SSE, the sum of the squared error of each measurement
## Compute n, the number of groups in the reduced model (ie. 1 for the overall mean)
## Compute df2, the residual degrees of freedom
(reduced <- reduced %>% 
  summarise(N = n(), sse = sum(sq_error)) %>% # sse = sum square error
  mutate(n = 1) %>% 
  mutate(df2 = N - n) %>% 
  select(sse, df2, N, n)
)
```

## Compute the SSA, df and MSA explained by the complete model
```{r }

## Residual variance of the reduced model explained by the complete model
(explained_ssa <- reduced$sse - complete$sse)

## df1 = number of groups (ie. individuals) - 1 (for the overall mean)
(explained_df1 <- reduced$df2 - complete$df2)

## MSA = SSA/df1
(explained_msa <- explained_ssa / explained_df1)

## Fratio = MSA/MSE
(f <- explained_msa / complete$mse)

## Compute P-value
pf(f, explained_df1, complete$df2, lower.tail = FALSE)
```

## Compute the repeatability
```{r }
## Number of replicates
num_rep <- complete$N/complete$n

## Within individual variance
(VarWithin <- complete$mse)

## Among individual variance 
(VarAmong<- (explained_msa-complete$mse)/num_rep)

## Observed repeatability
(Repeatability <- VarAmong/(VarAmong+VarWithin))

## Expected repeatability
(R_expected=var_among/(var_among+var_within))
```
